/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Counter: (() => {
      const tableId = new TableId("", "Counter");
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    MapLand: (() => {
      const tableId = new TableId("", "MapLand");
      return defineComponent(
        world,
        {
          tokenAddress: RecsType.String,
          tokenId: RecsType.BigInt,
          image: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    NftPosition: (() => {
      const tableId = new TableId("", "NftPosition");
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          landedDate: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
