// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapLand, MapLandData, MapLandTableId } from "./tables/MapLand.sol";
import { NftPosition, NftPositionData, NftPositionTableId } from "./tables/NftPosition.sol";
