// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IClaimBasedGhoulsSystem {
  function claimGhoul(
    bytes32 key,
    uint32 x,
    uint32 y,
    uint256 tokenId,
    string memory image,
    bytes memory signature,
    bytes32 storageRoot,
    bytes[] memory stateProof,
    bytes[] memory storageProof
  ) external;
}
